export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTARTION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const ITEMS_ADMIN_ROUTE = '/admin/items'
export const USERS_ADMIN_ROUTE = '/admin/users'
export const ORDERS_ADMIN_ROUTE = '/admin/orders'
export const CATALOG_ADMIN_ROUTE = '/admin/catalog'